apiVersion: v1
kind: Service
metadata:
  name: udagram-feed-api
  # namespace: my-namespace
  labels:
    app: udagram-feed-api
spec:
  selector:
    app: udagram-feed-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80